[package]
name = "rand_core"
version = "0.0.1"
authors = ["The Rust Project Developers"]
description = "Random number generator core: `Rng` and extensions"
homepage = "https://github.com/dhardy/rand/tree/master/rand_core"
documentation = "https://docs.rs/rand_core"
readme = "README.md"
keywords = ["random", "rng"]
categories = ["algorithms"]
license = "MIT/Apache-2.0"
repository = "https://github.com/dhardy/rand/"

[features]
default = ["std"]
nightly = ["i128_support"]
std = []
i128_support = []
